# Generated by Django 4.2 on 2026-05-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
