# Generated by Django 4.2 on 2026-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='rating',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
