# Generated by Django 4.2 on 2026-05-21 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0009_userrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
